//console.log("Hello, World");

//Function that generates a random outcome between the three choices.
function getComputerChoice() {
    const randomComputer = Math.floor(Math.random() * 3);
    if (randomComputer === 0) {
        return "rock";
    } else if (randomComputer === 1) {
        return "paper";
    } else {
        return "scissors";
    }
}


let humanScore = 0;  
let computerScore = 0;

// gets called when a button is clicked. Compares the choices and declares a winner
function playGame(computerChoice, userChoice) { 
    if (computerChoice === userChoice) {
        let tie = document.createElement("p");
        tie.textContent = "Tie!";
        showResults.appendChild(tie);
    } else if (computerChoice === "rock" && userChoice === "scissors" || computerChoice === "scissors" && userChoice  === "paper" || computerChoice === "paper" && userChoice === "rock") {
        computerScore++;
        const computerWins = document.createElement("p");
        computerWins.textContent = `Computer Wins! ${computerChoice} beats ${userChoice}.` 
        showResults.appendChild(computerWins);

    } else {
        humanScore++;
        const humanWins = document.createElement("p");
        humanWins.textContent = `You win! ${userChoice} beats ${computerChoice}.`;
        showResults.appendChild(humanWins);
    }

    //listens for when either the user or the computer accumulate 5 points and declares if the user wins or loses
    if (humanScore === 5 || computerScore === 5) {
        const showWinner = document.createElement("h3");
        showWinner.textContent = 
            humanScore === 5
                ? "Congratulation, You Won!"
                : "Sorry , You Lost!"
        fivePicksWinner.appendChild(showWinner);
        //remove all the informational text generated by  buttons clicks
        while (showResults.firstChild) {
            showResults.removeChild(showResults.lastChild);
        }
        //reset the scores
        humanScore = 0;
        computerScore = 0;
    }

}
// reference to the div containing the buttons
const choicesContainer = document.querySelector("#choices");

// add eventListener for clicks inside the div container 
choicesContainer.addEventListener("click", e => {
    // select only clicks on BUTTON elements
    if(e.target.tagName != "BUTTON" ) return;
    // assign the text of the id of the clicked button to the humanChoice variable
    const humanChoice = e.target.id;
    const computerChoice = getComputerChoice();
    playGame(computerChoice, humanChoice);
}) 

// div to which,in the playGame function, we append the element that contains the text generated by each button click
const showResults = document.querySelector("#eachPickWinner");

// "-----------------------------------", we append the element that contains the text generated when a five times win is reached 
const fivePicksWinner = document.querySelector("#fivePicksWinner");

